### ISSUE TITLE
这个表丢失?

### ISSUE THREAD

**Issue by jianwoo** [summerblue/laravel-shop#10]
SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) (SQL: select count(*) as aggregate from `products` where `on_sale` = 1)

**Comment by leo108** [comment]
数据库密码不对

**Comment by jianwoo** [comment]
密码是对的哈

**Comment by leo108** [comment]
建议你好好学英语

**Comment by jianwoo** [comment]
这个能等于密码不对?   牛逼
