### ISSUE TITLE
安装完成后，报404

### ISSUE THREAD

**Issue by xbpk3t** [summerblue/laravel-shop#30]
nginx日志如下；

➜  logs cat nginx_common_error.log
2019/02/01 15:22:54 [error] 71536#0: *41 open() "/Applications/MxSrvs/www/shop/public/products" failed (2: No such file or directory), client: 127.0.0.1, server: dev.shop.com, request: "GET /products HTTP/1.1", host: "dev.shop.com"

看了一下路由文件，好像没有什么问题；
翻了一下以前的issues，也没有类似的问题；

求助；

**Comment by majiameng** [comment]
没有数据库呀
