### ISSUE TITLE
es 添加数据的时候同事加入Es里面去了，那删除的时候呢

### ISSUE THREAD

**Issue by zenghuang19** [summerblue/laravel-shop#33]
es 添加数据的时候同事加入Es里面去了，那删除的时候呢

**Comment by leo108** [comment]
本项目没有实现商品删除功能，不过如果要实现的话，需要监听一下删除事件，清理 ES 中的对应数据。

**Comment by yuxiangwei** [comment]
为撒你的，数据表都是用MyISAM 不用InnoDB
