### ISSUE TITLE
php.exe artisan admin:install安装导致表编码和排序都是utf8mb4,不知是本地原因还是框架本身原因

### ISSUE THREAD

**Issue by tengfei31** [summerblue/laravel-shop#36]
我直接在GitHub上down下来的，分支(L05_5.7)
php.exe artisan admin:install安装导致表编码和排序都是utf8mb4,
错误：
Migrating: 2014_10_12_000000_create_users_table

   Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `users` add unique `users_email_unique`(`email`))

不知是本地原因还是框架本身原因
框架Laravel Framework 5.7.17
PHP 7.2.22 (cli) (built: Aug 28 2019 09:29:01) ( ZTS MSVC15 (Visual C++ 2017) x64 )
windows10
10.1.24-MariaDB, for Win32 (AMD64)

我创建的数据库是utf8 -- UTF-8 Unicode的编码以及utf8_general_ci排序

但是一执行artisan admin:install 就报错，把user表设置为了CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;，然后给email字段设置unique索引的时候就会报超出767个字节错误，我不能挨个改字段长度，我也不能挨个加编码，我只能手动改框架本身的设置，统一默认设置为utf8以及utf8_unicode_ci排序，
请问一下这是我操作的问题还是项目本身的问题？

**Comment by leo108** [comment]
https://www.google.com/search?q=Specified+key+was+too+long%3B+max+key+length+is+767+bytes

**Comment by tengfei31** [comment]
好的，谢谢了，thanks very match！！！
我的方法还得改源码，还是你这个办法好
